"""
data_pack.py
Grounded source data for Veridian Corp IT Support Agent.
Directly transcribed from the official assignment Data Pack.
"""

KNOWLEDGE_BASE = {
    "KB-01": {
        "id": "KB-01",
        "title": "Password Reset",
        "content": (
            "Employees can reset their own password via the self-service portal at any time. "
            "If locked out after 5 failed attempts, contact IT to unlock the account manually. "
            "No approval required."
        ),
        "category": "Identity & Access",
        "auto_resolvable": True,
        "requires_approval": False,
        "approval_authority": None
    },
    "KB-02": {
        "id": "KB-02",
        "title": "VPN Access",
        "content": (
            "VPN access is granted automatically to all full-time employees. Contractors require "
            "manager approval submitted via the access request form. VPN credentials expire every 90 days "
            "and must be renewed by the employee."
        ),
        "category": "Network & Access",
        "auto_resolvable": True,
        "requires_approval": True,
        "approval_authority": "Manager (for contractors)"
    },
    "KB-03": {
        "id": "KB-03",
        "title": "Laptop Replacement",
        "content": (
            "Laptops are eligible for replacement after 3 years of service, or earlier in case of "
            "verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."
        ),
        "category": "Hardware",
        "auto_resolvable": False,
        "requires_approval": True,
        "approval_authority": "IT & Finance (if outside standard cycle)"
    },
    "KB-04": {
        "id": "KB-04",
        "title": "Software Installation Requests",
        "content": (
            "Standard software (listed in the approved catalog) can be self-installed. "
            "Non-catalog software requires IT Security review, which takes 3–5 business days."
        ),
        "category": "Software & Applications",
        "auto_resolvable": False,
        "requires_approval": True,
        "approval_authority": "IT Security"
    },
    "KB-05": {
        "id": "KB-05",
        "title": "Printer Troubleshooting",
        "content": (
            "For printer issues, first check the printer queue and restart the print spooler. "
            "If the issue persists after restart, log a ticket with the printer’s asset tag."
        ),
        "category": "Office Hardware",
        "auto_resolvable": True,
        "requires_approval": False,
        "approval_authority": None
    },
    "KB-06": {
        "id": "KB-06",
        "title": "Email Mailbox Quota",
        "content": (
            "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. "
            "Quota increases beyond 25GB require manager approval and are capped at 50GB."
        ),
        "category": "Collaboration & Email",
        "auto_resolvable": False,
        "requires_approval": True,
        "approval_authority": "Manager"
    },
    "KB-07": {
        "id": "KB-07",
        "title": "Guest Wi-Fi Access",
        "content": (
            "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee "
            "from the front-desk kiosk. No IT ticket required."
        ),
        "category": "Network & Access",
        "auto_resolvable": True,
        "requires_approval": False,
        "approval_authority": None
    },
    "KB-08": {
        "id": "KB-08",
        "title": "Expense Software Access",
        "content": (
            "Access to the expense management tool is granted by Finance, not IT. "
            "IT can only assist with login/technical issues once an account already exists."
        ),
        "category": "Application Access / Cross-functional",
        "auto_resolvable": True,
        "requires_approval": True,
        "approval_authority": "Finance"
    },
    "KB-09": {
        "id": "KB-09",
        "title": "Security Incident Reporting",
        "content": (
            "Any suspected phishing email, malware, or unauthorized access attempt must be reported "
            "to security@veridian-corp.example immediately and should not be forwarded to other employees."
        ),
        "category": "Information Security",
        "auto_resolvable": False,
        "requires_approval": True,
        "approval_authority": "IT Security (CRITICAL ESCALATION)"
    },
    "KB-10": {
        "id": "KB-10",
        "title": "Work-From-Home Equipment",
        "content": (
            "Employees working remotely more than 3 days/week are eligible for a one-time home office "
            "equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — "
            "IT only handles the equipment shipping request once approved."
        ),
        "category": "Hardware & Facilities",
        "auto_resolvable": False,
        "requires_approval": True,
        "approval_authority": "Manager & Finance"
    },
    "ASSET-POL": {
        "id": "ASSET-POL",
        "title": "Asset Management Policy (Finance & Assets, Q2 2026)",
        "content": (
            "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle "
            "from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval."
        ),
        "category": "Governance & Finance",
        "auto_resolvable": False,
        "requires_approval": True,
        "approval_authority": "Finance & Assets + IT"
    }
}

EMPLOYEE_REQUESTS = [
    {
        "id": "REQ-01",
        "employee": "Aditi Sharma",
        "email": "aditi.sharma@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request": "My laptop won't turn on at all, it's completely dead, had it about 3.5 years now.",
        "initial_action": "Not started",
        "expected_policy": ["KB-03", "ASSET-POL"],
        "expected_action": "Escalate to Finance + IT (Verified hardware failure / Early replacement 3.5 yrs < 4 yrs cycle)"
    },
    {
        "id": "REQ-02",
        "employee": "Vikram Chawla",
        "email": "vikram.chawla@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request": "Can I get Wi-Fi access for a guest visiting our office tomorrow?",
        "initial_action": "Not started",
        "expected_policy": ["KB-07"],
        "expected_action": "Direct Self-Service Resolution (Front-desk kiosk generates 24h pass, no ticket needed)"
    },
    {
        "id": "REQ-03",
        "employee": "Karan Mehta",
        "email": "karan.mehta@veridian-corp.example",
        "date_opened": "Mon 21 Sep",
        "request": "I'm locked out of my account, tried my password 6 times.",
        "initial_action": "In progress — reset queued",
        "expected_policy": ["KB-01"],
        "expected_action": "IT Manual Account Unlock (Failed > 5 attempts; manual unlock execution)"
    },
    {
        "id": "REQ-04",
        "employee": "Ritu Bhatia",
        "email": "ritu.bhatia@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request": "Need approval to install a data-analysis tool that's not in the software catalog.",
        "initial_action": "Waiting on Security review",
        "expected_policy": ["KB-04"],
        "expected_action": "Escalate to IT Security Review (3–5 business days turnaround)"
    },
    {
        "id": "REQ-05",
        "employee": "Sanjay Oberoi",
        "email": "sanjay.oberoi@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request": "My VPN stopped working this morning, says credentials expired.",
        "initial_action": "Not started",
        "expected_policy": ["KB-02"],
        "expected_action": "Guide Self-Renewal (90-day renewal cycle policy; check FT vs Contractor status)"
    },
    {
        "id": "REQ-06",
        "employee": "Meera Iyer",
        "email": "meera.iyer@veridian-corp.example",
        "date_opened": "Tue 22 Sep",
        "request": "Printer on the 3rd floor keeps showing 'paper jam' even though there's no jam.",
        "initial_action": "Investigating — technician assigned",
        "expected_policy": ["KB-05"],
        "expected_action": "Troubleshoot spooler / Dispatch technician with asset tag"
    },
    {
        "id": "REQ-07",
        "employee": "Farhan Ali",
        "email": "farhan.ali@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": "I've started working from home 4 days a week, how do I get a monitor?",
        "initial_action": "Not started",
        "expected_policy": ["KB-10"],
        "expected_action": "Check >3 days WFH threshold -> Guide Manager sign-off & Finance approval first"
    },
    {
        "id": "REQ-08",
        "employee": "Ananya Reddy",
        "email": "ananya.reddy@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": "I think I got a phishing email asking for my login — forwarding it to a few teammates to check.",
        "initial_action": "Escalated to Security (auto-flagged)",
        "expected_policy": ["KB-09"],
        "expected_action": "CRITICAL INTERVENTION: Stop forwarding immediately, report to security@veridian-corp.example"
    },
    {
        "id": "REQ-09",
        "employee": "Rohit Desai",
        "email": "rohit.desai@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": "My mailbox is full and I can't send emails.",
        "initial_action": "Not started",
        "expected_policy": ["KB-06"],
        "expected_action": "Advise archiving old mail; guide manager approval for increase capped at 50GB"
    },
    {
        "id": "REQ-10",
        "employee": "Kavya Pillai",
        "email": "kavya.pillai@veridian-corp.example",
        "date_opened": "Wed 23 Sep",
        "request": "Can someone give me admin access to the finance reporting server? Need it urgently for month-end.",
        "initial_action": "Not started",
        "expected_policy": ["KB-08", "Precedent TK-1050"],
        "expected_action": "Reject / Escalate for formal business justification & Finance owner approval"
    },
    {
        "id": "REQ-11",
        "employee": "Nikhil Bansal",
        "email": "nikhil.bansal@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request": "New contractor joining my team next week, they'll need VPN access.",
        "initial_action": "Not started",
        "expected_policy": ["KB-02"],
        "expected_action": "Require manager approval via Access Request Form (Contractor policy requirement)"
    },
    {
        "id": "REQ-12",
        "employee": "Sneha Kulkarni",
        "email": "sneha.kulkarni@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request": "I can't log into the expense tool, keeps saying invalid credentials.",
        "initial_action": "Waiting on employee response (asked for a screenshot, no reply yet)",
        "expected_policy": ["KB-08"],
        "expected_action": "Clarify if account already created by Finance; if existing, troubleshoot login"
    },
    {
        "id": "REQ-13",
        "employee": "Aman Gupta",
        "email": "aman.gupta@veridian-corp.example",
        "date_opened": "Thu 24 Sep",
        "request": "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement.",
        "initial_action": "Not started",
        "expected_policy": ["KB-03", "ASSET-POL"],
        "expected_action": "Hardware repair triage (2 yrs not eligible for refresh; route to IT Hardware repair)"
    },
    {
        "id": "REQ-14",
        "employee": "Tanya Chopra",
        "email": "tanya.chopra@veridian-corp.example",
        "date_opened": "Fri 25 Sep",
        "request": "Requesting approval to install a browser extension for productivity tracking.",
        "initial_action": "Not started",
        "expected_policy": ["KB-04"],
        "expected_action": "Identify as non-catalog software; submit for IT Security 3–5 day review"
    },
    {
        "id": "REQ-15",
        "employee": "Rahul Menon",
        "email": "rahul.menon@veridian-corp.example",
        "date_opened": "Fri 25 Sep",
        "request": "hey can you help, its not working",
        "initial_action": "Not started",
        "expected_policy": ["General Triage"],
        "expected_action": "Ask clarifying diagnostic questions (Ambiguous intent / Missing asset/app details)"
    }
]

TICKET_QUEUE = [
    {
        "ticket_id": "TK-1042",
        "employee": "R. Verma",
        "issue_summary": "VPN credential expired",
        "status": "Resolved (closed)",
        "active": False,
        "resolution_pattern": "Self-renewed or renewed per KB-02 90-day policy"
    },
    {
        "ticket_id": "TK-1043",
        "employee": "S. Iyer",
        "issue_summary": "Laptop replacement (3.2 yrs old)",
        "status": "Approved — pending fulfillment (active)",
        "active": True,
        "resolution_pattern": "Required Finance exception sign-off because 3.2 yrs < 4 yr asset cycle"
    },
    {
        "ticket_id": "TK-1044",
        "employee": "A. Khan",
        "issue_summary": "Non-catalog software request",
        "status": "Pending Security review (active)",
        "active": True,
        "resolution_pattern": "Routed to IT Security queue per KB-04 (3-5 day SLA)"
    },
    {
        "ticket_id": "TK-1045",
        "employee": "P. Joshi",
        "issue_summary": "Mailbox quota increase",
        "status": "Approved at 35GB (closed)",
        "active": False,
        "resolution_pattern": "Approved with manager sign-off within 50GB cap per KB-06"
    },
    {
        "ticket_id": "TK-1046",
        "employee": "M. Das",
        "issue_summary": "Printer paper jam, floor 2",
        "status": "Resolved (closed)",
        "active": False,
        "resolution_pattern": "Hardware technician cleared jam per KB-05"
    },
    {
        "ticket_id": "TK-1047",
        "employee": "K. Singh",
        "issue_summary": "Home office equipment request",
        "status": "Pending Finance (active)",
        "active": True,
        "resolution_pattern": "Awaiting Finance processing after manager sign-off per KB-10"
    },
    {
        "ticket_id": "TK-1048",
        "employee": "T. Rao",
        "issue_summary": "Phishing email reported",
        "status": "Escalated to Security — under investigation (active)",
        "active": True,
        "resolution_pattern": "Quarantined and escalated to security@veridian-corp.example per KB-09"
    },
    {
        "ticket_id": "TK-1049",
        "employee": "V. Nambiar",
        "issue_summary": "Password reset",
        "status": "Resolved (closed)",
        "active": False,
        "resolution_pattern": "Manual IT account unlock performed after >5 lockout per KB-01"
    },
    {
        "ticket_id": "TK-1050",
        "employee": "J. Fernandes",
        "issue_summary": "Admin access request",
        "status": "Rejected — no business justification provided (closed)",
        "active": False,
        "resolution_pattern": "Precedent: Admin privileges rejected without verified business justification"
    },
    {
        "ticket_id": "TK-1051",
        "employee": "L. Menon",
        "issue_summary": "Guest Wi-Fi issued",
        "status": "Resolved (closed)",
        "active": False,
        "resolution_pattern": "Directed to front-desk kiosk for 24h credential per KB-07"
    }
]
